// NOTE: This file was generated by a tool.
#pragma once

#include <base.h>
#include "HookBaseProvider.h"
#include <Utilities\DebugBuffer.h>

namespace ReSoel {
    namespace Hooks {
        class ITrampolineClient;

        class GeneratedTrampolines
            : public HookBaseProvider<GeneratedTrampolines>
        {
        public:
            GeneratedTrampolines();
            static void SetTrampolineClient(std::shared_ptr<ITrampolineClient> client);

        private:
            HookTable BuildHookTable() const override sealed;

            static BOOL WINAPI AllocConsoleHookStatic();
            BOOL AllocConsoleHook();

            static BOOL WINAPI AttachConsoleHookStatic(DWORD dwProcessId);
            BOOL AttachConsoleHook(DWORD dwProcessId);

            static HANDLE WINAPI CreateConsoleScreenBufferHookStatic(DWORD dwDesiredAccess, DWORD dwShareMode, const SECURITY_ATTRIBUTES* lpSecurityAttributes, DWORD dwFLags, LPVOID lpScreenBufferData);
            HANDLE CreateConsoleScreenBufferHook(DWORD dwDesiredAccess, DWORD dwShareMode, const SECURITY_ATTRIBUTES* lpSecurityAttributes, DWORD dwFLags, LPVOID lpScreenBufferData);

            static BOOL WINAPI FillConsoleOutputAttributeHookStatic(HANDLE hConsoleOutput, WORD wAttribute, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfAttrsWritten);
            BOOL FillConsoleOutputAttributeHook(HANDLE hConsoleOutput, WORD wAttribute, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfAttrsWritten);

            static BOOL WINAPI FillConsoleOutputCharacterWHookStatic(HANDLE hConsoleOutput, WCHAR cCharacter, DWORD nLength, COORD dwWriterCoord, LPDWORD lpNumberOfCharsWritten);
            BOOL FillConsoleOutputCharacterWHook(HANDLE hConsoleOutput, WCHAR cCharacter, DWORD nLength, COORD dwWriterCoord, LPDWORD lpNumberOfCharsWritten);

            static BOOL WINAPI FillConsoleOutputCharacterAHookStatic(HANDLE hConsoleOutput, CHAR cCharacter, DWORD nLength, COORD dwWriterCoord, LPDWORD lpNumberOfCharsWritten);
            BOOL FillConsoleOutputCharacterAHook(HANDLE hConsoleOutput, CHAR cCharacter, DWORD nLength, COORD dwWriterCoord, LPDWORD lpNumberOfCharsWritten);

            static BOOL WINAPI FlushConsoleInputBufferHookStatic(HANDLE hConsoleInput);
            BOOL FlushConsoleInputBufferHook(HANDLE hConsoleInput);

            static BOOL WINAPI FreeConsoleHookStatic();
            BOOL FreeConsoleHook();

            static BOOL WINAPI ScrollConsoleScreenBufferWHookStatic(HANDLE hConsoleOutput, const SMALL_RECT* lpScrollRectangle, const SMALL_RECT* lpClipRectangle, COORD dwDestinationOrigin, const CHAR_INFO* lpFill);
            BOOL ScrollConsoleScreenBufferWHook(HANDLE hConsoleOutput, const SMALL_RECT* lpScrollRectangle, const SMALL_RECT* lpClipRectangle, COORD dwDestinationOrigin, const CHAR_INFO* lpFill);

            static BOOL WINAPI ScrollConsoleScreenBufferAHookStatic(HANDLE hConsoleOutput, const SMALL_RECT* lpScrollRectangle, const SMALL_RECT* lpClipRectangle, COORD dwDestinationOrigin, const CHAR_INFO* lpFill);
            BOOL ScrollConsoleScreenBufferAHook(HANDLE hConsoleOutput, const SMALL_RECT* lpScrollRectangle, const SMALL_RECT* lpClipRectangle, COORD dwDestinationOrigin, const CHAR_INFO* lpFill);

            static BOOL WINAPI SetConsoleActiveScreenBufferHookStatic(HANDLE hConsoleOutput);
            BOOL SetConsoleActiveScreenBufferHook(HANDLE hConsoleOutput);

            static BOOL WINAPI SetConsoleCPHookStatic(UINT wCodePageID);
            BOOL SetConsoleCPHook(UINT wCodePageID);

            static BOOL WINAPI SetConsoleCtrlHandlerHookStatic(PHANDLER_ROUTINE HandlerRoutine, BOOL Add);
            BOOL SetConsoleCtrlHandlerHook(PHANDLER_ROUTINE HandlerRoutine, BOOL Add);

            static BOOL WINAPI SetConsoleCursorInfoHookStatic(HANDLE hConsoleOutput, const CONSOLE_CURSOR_INFO* lpConsoleCursorInfo);
            BOOL SetConsoleCursorInfoHook(HANDLE hConsoleOutput, const CONSOLE_CURSOR_INFO* lpConsoleCursorInfo);

            static BOOL WINAPI SetConsoleCursorPositionHookStatic(HANDLE hConsoleOutput, COORD dwCursorPosition);
            BOOL SetConsoleCursorPositionHook(HANDLE hConsoleOutput, COORD dwCursorPosition);

            static BOOL WINAPI SetConsoleDisplayModeHookStatic(HANDLE hConsoleOutput, DWORD dwFlags, PCOORD lpNewScreenBufferDimensions);
            BOOL SetConsoleDisplayModeHook(HANDLE hConsoleOutput, DWORD dwFlags, PCOORD lpNewScreenBufferDimensions);

            static BOOL WINAPI SetConsoleModeHookStatic(HANDLE hConsoleHandle, DWORD dwMode);
            BOOL SetConsoleModeHook(HANDLE hConsoleHandle, DWORD dwMode);

            static BOOL WINAPI SetConsoleOutputCPHookStatic(UINT wCodePageId);
            BOOL SetConsoleOutputCPHook(UINT wCodePageId);

            static BOOL WINAPI SetConsoleScreenBufferInfoExHookStatic(HANDLE hConsoleOutput, PCONSOLE_SCREEN_BUFFER_INFOEX lpConsoleScreenBufferInfoEx);
            BOOL SetConsoleScreenBufferInfoExHook(HANDLE hConsoleOutput, PCONSOLE_SCREEN_BUFFER_INFOEX lpConsoleScreenBufferInfoEx);

            static BOOL WINAPI SetConsoleScreenBufferSizeHookStatic(HANDLE hConsoleOutput, COORD dwSize);
            BOOL SetConsoleScreenBufferSizeHook(HANDLE hConsoleOutput, COORD dwSize);

            static BOOL WINAPI SetConsoleTextAttributeHookStatic(HANDLE hConsoleOutput, WORD wAttributes);
            BOOL SetConsoleTextAttributeHook(HANDLE hConsoleOutput, WORD wAttributes);

            static BOOL WINAPI SetConsoleTitleWHookStatic(WCHAR* lpConsoleTitle);
            BOOL SetConsoleTitleWHook(WCHAR* lpConsoleTitle);

            static BOOL WINAPI SetConsoleTitleAHookStatic(CHAR* lpConsoleTitle);
            BOOL SetConsoleTitleAHook(CHAR* lpConsoleTitle);

            static BOOL WINAPI SetConsoleWindowInfoHookStatic(HANDLE hConsoleOutput, BOOL bAbsolute, const SMALL_RECT* lpConsoleWindow);
            BOOL SetConsoleWindowInfoHook(HANDLE hConsoleOutput, BOOL bAbsolute, const SMALL_RECT* lpConsoleWindow);

            static BOOL WINAPI SetCurrentConsoleFontExHookStatic(HANDLE hConsoleOutput, BOOL bMaximumWindow, PCONSOLE_FONT_INFOEX lpConsoleCurrentFontEx);
            BOOL SetCurrentConsoleFontExHook(HANDLE hConsoleOutput, BOOL bMaximumWindow, PCONSOLE_FONT_INFOEX lpConsoleCurrentFontEx);

            static BOOL WINAPI SetStdHandleHookStatic(DWORD nStdHandle, HANDLE hHandle);
            BOOL SetStdHandleHook(DWORD nStdHandle, HANDLE hHandle);

            static BOOL WINAPI WriteConsoleWHookStatic(HANDLE hConsoleOutput, const VOID* lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved);
            BOOL WriteConsoleWHook(HANDLE hConsoleOutput, const VOID* lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved);

            static BOOL WINAPI WriteConsoleAHookStatic(HANDLE hConsoleOutput, const VOID* lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved);
            BOOL WriteConsoleAHook(HANDLE hConsoleOutput, const VOID* lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved);

            static BOOL WINAPI WriteConsoleOutputWHookStatic(HANDLE hConsoleOutput, const CHAR_INFO* lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, PSMALL_RECT lpWriteRegion);
            BOOL WriteConsoleOutputWHook(HANDLE hConsoleOutput, const CHAR_INFO* lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, PSMALL_RECT lpWriteRegion);

            static BOOL WINAPI WriteConsoleOutputAHookStatic(HANDLE hConsoleOutput, const CHAR_INFO* lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, PSMALL_RECT lpWriteRegion);
            BOOL WriteConsoleOutputAHook(HANDLE hConsoleOutput, const CHAR_INFO* lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, PSMALL_RECT lpWriteRegion);

            static BOOL WINAPI WriteConsoleOutputAttributeHookStatic(HANDLE hConsoleOutput, const WORD* lpAttribute, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfAttrsWritten);
            BOOL WriteConsoleOutputAttributeHook(HANDLE hConsoleOutput, const WORD* lpAttribute, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfAttrsWritten);

            static BOOL WINAPI WriteConsoleOutputCharacterWHookStatic(HANDLE hConsoleOutput, WCHAR* lpCharacter, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfCharsWritten);
            BOOL WriteConsoleOutputCharacterWHook(HANDLE hConsoleOutput, WCHAR* lpCharacter, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfCharsWritten);

            static BOOL WINAPI WriteConsoleOutputCharacterAHookStatic(HANDLE hConsoleOutput, CHAR* lpCharacter, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfCharsWritten);
            BOOL WriteConsoleOutputCharacterAHook(HANDLE hConsoleOutput, CHAR* lpCharacter, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfCharsWritten);

            static BOOL WINAPI WriteFileHookStatic(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
            BOOL WriteFileHook(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);


            std::shared_ptr<ITrampolineClient> m_client;
            ReSoel::Utilities::DebugBuffer m_debugBuffer;
            std::ostream m_debugOut;
        };
    }
}
